### ISSUE TITLE
release jar

### ISSUE THREAD

**Issue by regular-snow** [kybe236/rusherhack-mace-kill#1]
why is the jar in release obfuscated

**Comment by kybe236** [comment]
it shouldn't what decompiler did you use.
for me its fine with jd-gui
![image](https://github.com/user-attachments/assets/b18c081d-1b82-49ed-926e-bc3ad6227836)

**Comment by kybe236** [comment]
if you mean the classes it is classic minecraft mapping.
https://wagyourtail.xyz/Projects/MinecraftMappingViewer/App
use it to get the classes
![image](https://github.com/user-attachments/assets/fcbfc552-17f3-4779-bbbe-4bbfca6a8749)
